baseURL = "https://trinkets.tech"
languageCode = "en"
title = "Trinkets blog and docs"
description = "Trinkets blog and docs"
copyright = "&copy; <a href=\"https://github.com/ShinyTrinkets/\">Shiny-Trinkets</a> 2018-2019"
disqusShortname = "https-trinkets-tech"

paginate = 5

[author]
  name = "CroQ"
  url = "https://github.com/croqaz/"

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/ShinyTrinkets/"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://gitlab.com/ShinyTrinkets/"
  fa_icon = "fab fa-gitlab"

[[params.social]]
  url = "https://reddit.com/r/ShinyTrinkets/"
  fa_icon = "fab fa-reddit"
